%% Personality Ontology - Defines character traits and behavioral tendencies

%% Dynamic and incremental tabling declarations for personality predicates
%% Ensures efficient querying and updates of the personality knowledge base
:- table (ambitious/1, disciplined/1, sensitive/1, cupid/1, 
    brave/1, ascetic/1, coward/1) as (incremental, dynamic).

:- discontiguous [personality/1, ambitious/1, disciplined/1, sensitive/1, cupid/1, brave/1, ascetic/1, coward/1].

%% Personality Hierarchy
%% Main categories of personalities that influence agent behavior:
%% - ambitious: goal-oriented and achievement-focused traits
%% - disciplined: self-controlled and methodical traits
%% - sensitive: emotionally responsive traits
personality(X) :- ambitious(X).
personality(X) :- disciplined(X).
personality(X) :- sensitive(X).

%% Ambitious Personalities
%% Characters driven by achievement and conquest:
%% - cupid: motivated by acquisition and wealth
%% - brave: motivated by combat and challenges
ambitious(X) :- cupid(X).
ambitious(X) :- brave(X).

%% Disciplined Personalities
%% Characters with strong self-control:
%% - ascetic: practices self-denial and restraint
disciplined(X) :- ascetic(X).

%% Sensitive Personalities
%% Characters with heightened emotional responses:
%% - coward: prioritizes safety and avoidance of danger
sensitive(X) :- coward(X).

%% Example Personality Facts generated by Unity as assertz
% cupid([human0, [_, _]]).
% brave([human0, [_, _]]).
% personality([human1, [_, _]]).
% ambitious([human2, [_, _]]).